name: Build

on: [push]

jobs:
  build:
    name: Re:VIEW Workflow
    runs-on: ubuntu-latest
    container: docker://vvakame/review:3.1
    steps:
      - uses: actions/checkout@v3
      - name: Install md2review gem
        run: gem install md2review
      - name: Convert MD to Re:VIEW
        run: sh convert-markdown.sh
      - name: Show review files
        run: ls src/*.re
      - name: Create PDF
        run: |
          cd src
          review pdfmaker config-print.yml
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: src/*.pdf
          retention-days: 3
